### ISSUE TITLE
why installcheck error?

### ISSUE THREAD

**Issue by yuql** [postgrespro/imgsmlr#1]
[postgres@localhost imgsmlr]$ **make USE_PGXS=1 installcheck**
    /usr/pgsql-9.6/lib/pgxs/src/makefiles/../../src/test/regress/pg_regress --inputdir=./ --bindir='/usr/pgsql-9.6/bin' --dbname=contrib_regression imgsmlr

    (using postmaster on Unix socket, default port)

    ============== dropping database "contrib_regression" ==============

    DROP DATABASE

    ============== creating database "contrib_regression" ==============

    CREATE DATABASE

    ALTER DATABASE

    ============== running regression test queries ==============

    test imgsmlr ... FAILED

    ======================

    1 of 1 tests failed.

    ======================

    The differences that caused some tests to fail can be viewed in the file "/soft/imgsmlr/regression.diffs". A copy of the test summary that you see

    above is saved in the file "/soft/imgsmlr/regression.out".

-----------------------------------------------------------------------------------------------------------
------------------------------------parts of regression.diffs-----------------------------------------------
*** 59,175 ****

id | id | round

----+----+--------

1 |  1 | 0.0000

! 1 | 2 | 1.5429

! 1 | 3 | 1.6181

! 1 | 4 | 2.8538

! 1 | 5 | 3.1795

! 1 | 6 | 2.7229

! 1 | 7 | 3.7688

! 1 | 8 | 3.8711

! 1 | 9 | 3.8873

! 1 | 10 | 4.7480

! 1 | 11 | 4.3794

! 1 | 12 | 3.5524

! 2 | 1 | 1.5429

2 |  2 | 0.0000

2 |  3 | 1.2565

2 |  4 | 2.7438

2 |  5 | 2.8960

**Comment by digoal** [comment]
```
*** /home/digoal/imgsmlr/expected/imgsmlr.out 2017-02-20 09:27:22.795198577 +0800
--- /home/digoal/imgsmlr/results/imgsmlr.out  2017-05-03 10:59:35.035102263 +0800
***************
*** 59,175 ****
   id | id | round  
  ----+----+--------
    1 |  1 | 0.0000
!   1 |  2 | 1.5429
!   1 |  3 | 1.6181
!   1 |  4 | 2.8538
!   1 |  5 | 3.1795
!   1 |  6 | 2.7229
!   1 |  7 | 3.7688
!   1 |  8 | 3.8711
!   1 |  9 | 3.8873
!   1 | 10 | 4.7480
!   1 | 11 | 4.3794
!   1 | 12 | 3.5524
!   2 |  1 | 1.5429
    2 |  2 | 0.0000
    2 |  3 | 1.2565
    2 |  4 | 2.7438
    2 |  5 | 2.8960
    2 |  6 | 2.6721
!   2 |  7 | 3.7888
    2 |  8 | 3.8436
    2 |  9 | 3.8618
    2 | 10 | 4.9851
    2 | 11 | 4.5120
    2 | 12 | 3.7382
!   3 |  1 | 1.6181
    3 |  2 | 1.2565
    3 |  3 | 0.0000
!   3 |  4 | 2.7838
    3 |  5 | 3.0885
    3 |  6 | 2.7983
!   3 |  7 | 3.8348
    3 |  8 | 3.9139
    3 |  9 | 3.9276
    3 | 10 | 4.8350
    3 | 11 | 4.4051
    3 | 12 | 3.6227
!   4 |  1 | 2.8538
    4 |  2 | 2.7438
!   4 |  3 | 2.7838
    4 |  4 | 0.0000
!   4 |  5 | 2.4290
    4 |  6 | 2.0993
!   4 |  7 | 3.7301
!   4 |  8 | 3.6740
!   4 |  9 | 3.6905
!   4 | 10 | 5.0571
!   4 | 11 | 4.6159
!   4 | 12 | 3.8774
!   5 |  1 | 3.1795
    5 |  2 | 2.8960
    5 |  3 | 3.0885
!   5 |  4 | 2.4290
    5 |  5 | 0.0000
    5 |  6 | 2.9476
!   5 |  7 | 3.5129
    5 |  8 | 3.4678
    5 |  9 | 3.4861
    5 | 10 | 5.1824
    5 | 11 | 4.7274
    5 | 12 | 3.8656
!   6 |  1 | 2.7229
    6 |  2 | 2.6721
    6 |  3 | 2.7983
    6 |  4 | 2.0993
    6 |  5 | 2.9476
    6 |  6 | 0.0000
!   6 |  7 | 3.6669
    6 |  8 | 3.7291
    6 |  9 | 3.7493
    6 | 10 | 5.1358
    6 | 11 | 4.5512
    6 | 12 | 3.9189
!   7 |  1 | 3.7688
!   7 |  2 | 3.7888
!   7 |  3 | 3.8348
!   7 |  4 | 3.7301
!   7 |  5 | 3.5129
!   7 |  6 | 3.6669
    7 |  7 | 0.0000
!   7 |  8 | 1.2444
!   7 |  9 | 1.2552
    7 | 10 | 5.0763
!   7 | 11 | 4.6689
!   7 | 12 | 4.0877
!   8 |  1 | 3.8711
    8 |  2 | 3.8436
    8 |  3 | 3.9139
!   8 |  4 | 3.6740
    8 |  5 | 3.4678
    8 |  6 | 3.7291
!   8 |  7 | 1.2444
    8 |  8 | 0.0000
    8 |  9 | 0.0381
    8 | 10 | 5.2375
    8 | 11 | 4.8223
    8 | 12 | 4.1483
!   9 |  1 | 3.8873
    9 |  2 | 3.8618
    9 |  3 | 3.9276
!   9 |  4 | 3.6905
    9 |  5 | 3.4861
    9 |  6 | 3.7493
!   9 |  7 | 1.2552
    9 |  8 | 0.0381
    9 |  9 | 0.0000
    9 | 10 | 5.2390
    9 | 11 | 4.8233
    9 | 12 | 4.1534
!  10 |  1 | 4.7480
   10 |  2 | 4.9851
   10 |  3 | 4.8350
!  10 |  4 | 5.0571
   10 |  5 | 5.1824
   10 |  6 | 5.1358
   10 |  7 | 5.0763
--- 59,175 ----
   id | id | round  
  ----+----+--------
    1 |  1 | 0.0000
!   1 |  2 | 1.5499
!   1 |  3 | 1.6159
!   1 |  4 | 2.8597
!   1 |  5 | 3.1844
!   1 |  6 | 2.7292
!   1 |  7 | 3.7746
!   1 |  8 | 3.8756
!   1 |  9 | 3.8916
!   1 | 10 | 4.7468
!   1 | 11 | 4.3770
!   1 | 12 | 3.5522
!   2 |  1 | 1.5499
    2 |  2 | 0.0000
    2 |  3 | 1.2565
    2 |  4 | 2.7438
    2 |  5 | 2.8960
    2 |  6 | 2.6721
!   2 |  7 | 3.7896
    2 |  8 | 3.8436
    2 |  9 | 3.8618
    2 | 10 | 4.9851
    2 | 11 | 4.5120
    2 | 12 | 3.7382
!   3 |  1 | 1.6159
    3 |  2 | 1.2565
    3 |  3 | 0.0000
!   3 |  4 | 2.7837
    3 |  5 | 3.0885
    3 |  6 | 2.7983
!   3 |  7 | 3.8356
    3 |  8 | 3.9139
    3 |  9 | 3.9276
    3 | 10 | 4.8350
    3 | 11 | 4.4051
    3 | 12 | 3.6227
!   4 |  1 | 2.8597
    4 |  2 | 2.7438
!   4 |  3 | 2.7837
    4 |  4 | 0.0000
!   4 |  5 | 2.4292
    4 |  6 | 2.0993
!   4 |  7 | 3.7311
!   4 |  8 | 3.6741
!   4 |  9 | 3.6906
!   4 | 10 | 5.0569
!   4 | 11 | 4.6157
!   4 | 12 | 3.8772
!   5 |  1 | 3.1844
    5 |  2 | 2.8960
    5 |  3 | 3.0885
!   5 |  4 | 2.4292
    5 |  5 | 0.0000
    5 |  6 | 2.9476
!   5 |  7 | 3.5138
    5 |  8 | 3.4678
    5 |  9 | 3.4861
    5 | 10 | 5.1824
    5 | 11 | 4.7274
    5 | 12 | 3.8656
!   6 |  1 | 2.7292
    6 |  2 | 2.6721
    6 |  3 | 2.7983
    6 |  4 | 2.0993
    6 |  5 | 2.9476
    6 |  6 | 0.0000
!   6 |  7 | 3.6673
    6 |  8 | 3.7291
    6 |  9 | 3.7493
    6 | 10 | 5.1358
    6 | 11 | 4.5512
    6 | 12 | 3.9189
!   7 |  1 | 3.7746
!   7 |  2 | 3.7896
!   7 |  3 | 3.8356
!   7 |  4 | 3.7311
!   7 |  5 | 3.5138
!   7 |  6 | 3.6673
    7 |  7 | 0.0000
!   7 |  8 | 1.2451
!   7 |  9 | 1.2558
    7 | 10 | 5.0763
!   7 | 11 | 4.6685
!   7 | 12 | 4.0880
!   8 |  1 | 3.8756
    8 |  2 | 3.8436
    8 |  3 | 3.9139
!   8 |  4 | 3.6741
    8 |  5 | 3.4678
    8 |  6 | 3.7291
!   8 |  7 | 1.2451
    8 |  8 | 0.0000
    8 |  9 | 0.0381
    8 | 10 | 5.2375
    8 | 11 | 4.8223
    8 | 12 | 4.1483
!   9 |  1 | 3.8916
    9 |  2 | 3.8618
    9 |  3 | 3.9276
!   9 |  4 | 3.6906
    9 |  5 | 3.4861
    9 |  6 | 3.7493
!   9 |  7 | 1.2558
    9 |  8 | 0.0381
    9 |  9 | 0.0000
    9 | 10 | 5.2390
    9 | 11 | 4.8233
    9 | 12 | 4.1534
!  10 |  1 | 4.7468
   10 |  2 | 4.9851
   10 |  3 | 4.8350
!  10 |  4 | 5.0569
   10 |  5 | 5.1824
   10 |  6 | 5.1358
   10 |  7 | 5.0763
***************
*** 178,202 ****
   10 | 10 | 0.0000
   10 | 11 | 3.0531
   10 | 12 | 3.1209
!  11 |  1 | 4.3794
   11 |  2 | 4.5120
   11 |  3 | 4.4051
!  11 |  4 | 4.6159
   11 |  5 | 4.7274
   11 |  6 | 4.5512
!  11 |  7 | 4.6689
   11 |  8 | 4.8223
   11 |  9 | 4.8233
   11 | 10 | 3.0531
   11 | 11 | 0.0000
   11 | 12 | 3.1781
!  12 |  1 | 3.5524
   12 |  2 | 3.7382
   12 |  3 | 3.6227
!  12 |  4 | 3.8774
   12 |  5 | 3.8656
   12 |  6 | 3.9189
!  12 |  7 | 4.0877
   12 |  8 | 4.1483
   12 |  9 | 4.1534
   12 | 10 | 3.1209
--- 178,202 ----
   10 | 10 | 0.0000
   10 | 11 | 3.0531
   10 | 12 | 3.1209
!  11 |  1 | 4.3770
   11 |  2 | 4.5120
   11 |  3 | 4.4051
!  11 |  4 | 4.6157
   11 |  5 | 4.7274
   11 |  6 | 4.5512
!  11 |  7 | 4.6685
   11 |  8 | 4.8223
   11 |  9 | 4.8233
   11 | 10 | 3.0531
   11 | 11 | 0.0000
   11 | 12 | 3.1781
!  12 |  1 | 3.5522
   12 |  2 | 3.7382
   12 |  3 | 3.6227
!  12 |  4 | 3.8772
   12 |  5 | 3.8656
   12 |  6 | 3.9189
!  12 |  7 | 4.0880
   12 |  8 | 4.1483
   12 |  9 | 4.1534
   12 | 10 | 3.1209
***************
*** 208,351 ****
   id | id | round  
  ----+----+--------
    1 |  1 | 0.0000
!   1 |  2 | 1.1725
!   1 |  3 | 1.2700
!   1 |  4 | 2.2873
!   1 |  5 | 2.7604
!   1 |  6 | 3.0463
!   1 |  7 | 6.2733
!   1 |  8 | 6.8493
!   1 |  9 | 6.9137
!   1 | 10 | 8.1533
!   1 | 11 | 6.7413
!   1 | 12 | 4.9751
!   2 |  1 | 1.1725
    2 |  2 | 0.0000
    2 |  3 | 1.5529
!   2 |  4 | 2.2927
    2 |  5 | 2.5661
    2 |  6 | 2.8778
!   2 |  7 | 6.5639
    2 |  8 | 7.0845
    2 |  9 | 7.1539
    2 | 10 | 8.8589
    2 | 11 | 7.2514
    2 | 12 | 5.6008
!   3 |  1 | 1.2700
    3 |  2 | 1.5529
    3 |  3 | 0.0000
    3 |  4 | 2.1051
    3 |  5 | 2.7715
    3 |  6 | 2.9852
!   3 |  7 | 6.0205
    3 |  8 | 6.5183
    3 |  9 | 6.5775
    3 | 10 | 8.1154
    3 | 11 | 6.4471
    3 | 12 | 4.8710
!   4 |  1 | 2.2873
!   4 |  2 | 2.2927
    4 |  3 | 2.1051
    4 |  4 | 0.0000
!   4 |  5 | 1.1985
!   4 |  6 | 1.5255
!   4 |  7 | 5.3554
!   4 |  8 | 5.8051
    4 |  9 | 5.8699
!   4 | 10 | 7.7219
!   4 | 11 | 5.9453
!   4 | 12 | 4.3425
!   5 |  1 | 2.7604
    5 |  2 | 2.5661
    5 |  3 | 2.7715
!   5 |  4 | 1.1985
    5 |  5 | 0.0000
    5 |  6 | 1.4203
!   5 |  7 | 5.8093
    5 |  8 | 6.2350
    5 |  9 | 6.3026
    5 | 10 | 8.0931
    5 | 11 | 6.4254
    5 | 12 | 4.7236
!   6 |  1 | 3.0463
    6 |  2 | 2.8778
    6 |  3 | 2.9852
!   6 |  4 | 1.5255
    6 |  5 | 1.4203
    6 |  6 | 0.0000
!   6 |  7 | 5.6890
    6 |  8 | 6.1441
    6 |  9 | 6.2102
    6 | 10 | 7.5542
    6 | 11 | 5.5261
    6 | 12 | 4.0463
!   7 |  1 | 6.2733
!   7 |  2 | 6.5639
!   7 |  3 | 6.0205
!   7 |  4 | 5.3554
!   7 |  5 | 5.8093
!   7 |  6 | 5.6890
    7 |  7 | 0.0000
!   7 |  8 | 1.3940
!   7 |  9 | 1.4256
!   7 | 10 | 8.7993
!   7 | 11 | 7.0273
!   7 | 12 | 6.5809
!   8 |  1 | 6.8493
    8 |  2 | 7.0845
    8 |  3 | 6.5183
!   8 |  4 | 5.8051
    8 |  5 | 6.2350
    8 |  6 | 6.1441
!   8 |  7 | 1.3940
    8 |  8 | 0.0000
    8 |  9 | 0.0845
    8 | 10 | 9.3799
    8 | 11 | 7.5065
    8 | 12 | 7.1548
!   9 |  1 | 6.9137
    9 |  2 | 7.1539
    9 |  3 | 6.5775
    9 |  4 | 5.8699
    9 |  5 | 6.3026
    9 |  6 | 6.2102
!   9 |  7 | 1.4256
    9 |  8 | 0.0845
    9 |  9 | 0.0000
    9 | 10 | 9.3937
    9 | 11 | 7.5250
    9 | 12 | 7.1905
!  10 |  1 | 8.1533
   10 |  2 | 8.8589
   10 |  3 | 8.1154
!  10 |  4 | 7.7219
   10 |  5 | 8.0931
   10 |  6 | 7.5542
!  10 |  7 | 8.7993
   10 |  8 | 9.3799
   10 |  9 | 9.3937
   10 | 10 | 0.0000
   10 | 11 | 3.6582
   10 | 12 | 4.1658
!  11 |  1 | 6.7413
   11 |  2 | 7.2514
   11 |  3 | 6.4471
!  11 |  4 | 5.9453
   11 |  5 | 6.4254
   11 |  6 | 5.5261
!  11 |  7 | 7.0273
   11 |  8 | 7.5065
   11 |  9 | 7.5250
   11 | 10 | 3.6582
   11 | 11 | 0.0000
   11 | 12 | 2.6022
!  12 |  1 | 4.9751
   12 |  2 | 5.6008
   12 |  3 | 4.8710
!  12 |  4 | 4.3425
   12 |  5 | 4.7236
   12 |  6 | 4.0463
!  12 |  7 | 6.5809
   12 |  8 | 7.1548
   12 |  9 | 7.1905
   12 | 10 | 4.1658
--- 208,351 ----
   id | id | round  
  ----+----+--------
    1 |  1 | 0.0000
!   1 |  2 | 1.1922
!   1 |  3 | 1.2584
!   1 |  4 | 2.2897
!   1 |  5 | 2.7684
!   1 |  6 | 3.0550
!   1 |  7 | 6.2689
!   1 |  8 | 6.8432
!   1 |  9 | 6.9075
!   1 | 10 | 8.1408
!   1 | 11 | 6.7314
!   1 | 12 | 4.9664
!   2 |  1 | 1.1922
    2 |  2 | 0.0000
    2 |  3 | 1.5529
!   2 |  4 | 2.2929
    2 |  5 | 2.5661
    2 |  6 | 2.8778
!   2 |  7 | 6.5656
    2 |  8 | 7.0845
    2 |  9 | 7.1539
    2 | 10 | 8.8589
    2 | 11 | 7.2514
    2 | 12 | 5.6008
!   3 |  1 | 1.2584
    3 |  2 | 1.5529
    3 |  3 | 0.0000
    3 |  4 | 2.1051
    3 |  5 | 2.7715
    3 |  6 | 2.9852
!   3 |  7 | 6.0218
    3 |  8 | 6.5183
    3 |  9 | 6.5775
    3 | 10 | 8.1154
    3 | 11 | 6.4471
    3 | 12 | 4.8710
!   4 |  1 | 2.2897
!   4 |  2 | 2.2929
    4 |  3 | 2.1051
    4 |  4 | 0.0000
!   4 |  5 | 1.1988
!   4 |  6 | 1.5256
!   4 |  7 | 5.3567
!   4 |  8 | 5.8050
    4 |  9 | 5.8699
!   4 | 10 | 7.7217
!   4 | 11 | 5.9451
!   4 | 12 | 4.3423
!   5 |  1 | 2.7684
    5 |  2 | 2.5661
    5 |  3 | 2.7715
!   5 |  4 | 1.1988
    5 |  5 | 0.0000
    5 |  6 | 1.4203
!   5 |  7 | 5.8110
    5 |  8 | 6.2350
    5 |  9 | 6.3026
    5 | 10 | 8.0931
    5 | 11 | 6.4254
    5 | 12 | 4.7236
!   6 |  1 | 3.0550
    6 |  2 | 2.8778
    6 |  3 | 2.9852
!   6 |  4 | 1.5256
    6 |  5 | 1.4203
    6 |  6 | 0.0000
!   6 |  7 | 5.6900
    6 |  8 | 6.1441
    6 |  9 | 6.2102
    6 | 10 | 7.5542
    6 | 11 | 5.5261
    6 | 12 | 4.0463
!   7 |  1 | 6.2689
!   7 |  2 | 6.5656
!   7 |  3 | 6.0218
!   7 |  4 | 5.3567
!   7 |  5 | 5.8110
!   7 |  6 | 5.6900
    7 |  7 | 0.0000
!   7 |  8 | 1.3937
!   7 |  9 | 1.4251
!   7 | 10 | 8.7983
!   7 | 11 | 7.0260
!   7 | 12 | 6.5807
!   8 |  1 | 6.8432
    8 |  2 | 7.0845
    8 |  3 | 6.5183
!   8 |  4 | 5.8050
    8 |  5 | 6.2350
    8 |  6 | 6.1441
!   8 |  7 | 1.3937
    8 |  8 | 0.0000
    8 |  9 | 0.0845
    8 | 10 | 9.3799
    8 | 11 | 7.5065
    8 | 12 | 7.1548
!   9 |  1 | 6.9075
    9 |  2 | 7.1539
    9 |  3 | 6.5775
    9 |  4 | 5.8699
    9 |  5 | 6.3026
    9 |  6 | 6.2102
!   9 |  7 | 1.4251
    9 |  8 | 0.0845
    9 |  9 | 0.0000
    9 | 10 | 9.3937
    9 | 11 | 7.5250
    9 | 12 | 7.1905
!  10 |  1 | 8.1408
   10 |  2 | 8.8589
   10 |  3 | 8.1154
!  10 |  4 | 7.7217
   10 |  5 | 8.0931
   10 |  6 | 7.5542
!  10 |  7 | 8.7983
   10 |  8 | 9.3799
   10 |  9 | 9.3937
   10 | 10 | 0.0000
   10 | 11 | 3.6582
   10 | 12 | 4.1658
!  11 |  1 | 6.7314
   11 |  2 | 7.2514
   11 |  3 | 6.4471
!  11 |  4 | 5.9451
   11 |  5 | 6.4254
   11 |  6 | 5.5261
!  11 |  7 | 7.0260
   11 |  8 | 7.5065
   11 |  9 | 7.5250
   11 | 10 | 3.6582
   11 | 11 | 0.0000
   11 | 12 | 2.6022
!  12 |  1 | 4.9664
   12 |  2 | 5.6008
   12 |  3 | 4.8710
!  12 |  4 | 4.3423
   12 |  5 | 4.7236
   12 |  6 | 4.0463
!  12 |  7 | 6.5807
   12 |  8 | 7.1548
   12 |  9 | 7.1905
   12 | 10 | 4.1658

======================================================================
```

**Comment by unyqhz** [comment]
have you solved this problem yet?

**Comment by akorotkov** [comment]
Regression tests wasn't changes according to fix in the signature calculation.
Could you try it with current master?

**Comment by unyqhz** [comment]
sorry，I am new to this,and I don't understand what you have said.Could you explain it in more detail? how can I compile it?

**Comment by unyqhz** [comment]
what do you mean by current master?

**Comment by akorotkov** [comment]
I've fixed it in 7ea9b21e6.  Please see readme for installation instructions:
https://github.com/postgrespro/imgsmlr/blob/master/README.md

**Comment by unyqhz** [comment]
thanks so much! Спасибо !

**Comment by unyqhz** [comment]
gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fpic -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o imgsmlr.o imgsmlr.c
imgsmlr.c: In function ‘read_float’:
imgsmlr.c:319:2: warning: implicit declaration of function ‘float8in_internal’ [-Wimplicit-function-declaration]
  return (float) float8in_internal(*s, s, type_name, orig_string);
  ^
gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fpic -shared -o imgsmlr.so imgsmlr.o imgsmlr_idx.o -L/usr/lib64 -Wl,-z,relro   -Wl,--as-needed  -lgd 
_______________________________________________________________________________________________________
ERROR:  could not load library "/usr/lib64/pgsql/imgsmlr.so": /usr/lib64/pgsql/imgsmlr.so: undefined symbol: float8in_internal

**Comment by unyqhz** [comment]
there seems another problem,when i use make USE_PGXS=1 ,there is a warning about float8in_internal,and when I use psql DB -c "CREATE EXTENSION imgsmlr;",another error about float8in_internal occured,but I checked and find you have included #include "utils/builtins.h" in imgsmlr.c.
Could you help me find out what's wrong ?

**Comment by akorotkov** [comment]
It appears that float8in_internal() was introduced only in 9.6.
I'll try provide implementation for pre 9.6 versions without using this functions.

**Comment by akorotkov** [comment]
Builds on pre 9.6 versions should be fixed since 54fa3625.

**Comment by akorotkov** [comment]
Regression tests were fixed as reported in #4.  Builds and tests on PostgreSQL 9.5+ are automatically tested in travis-ci.  So, I'm closing this issue.  Feel free to reopen if problem arises again.
